In [1]:
import sqlite3
import pandas as pd

con = sqlite3.connect('C:\\Users\\ctabd\\OneDrive\\Desktop\\3rd Sem ojt\\project_3.1\\2_IPL_Cricket\\ipl.db')

def q(sql):
    return pd.read_sql_query(sql, con)

In [2]:
def run_sql_file(path):
    with open(path,'r')as f:
        script=f.read()
    con.executescript(script)
    con.commit()
    print('ran',path)

In [3]:
q("""
-- What is the strike rate of every batter in the death overs

SELECT
    batter,
    ROUND(
        100.0 * SUM(batter_runs) /
        SUM(
            CASE
                WHEN is_wide_ball = 0
                 AND is_no_ball = 0
                THEN 1
                ELSE 0
            END
        ),
        2
    ) AS strike_rate
FROM deliveries
WHERE over_number >= 15
  AND is_super_over = 0
GROUP BY batter;
""")

             batter  strike_rate
0    A Ashish Reddy       146.58
1          A Badoni       165.03
2        A Chandila        57.14
3          A Chopra        50.00
4       A Choudhary       125.00
..              ...          ...
637      Yash Dayal        50.00
638   Yashpal Singh       130.77
639   Yudhvir Singh       166.67
640    Yuvraj Singh       183.40
641          Z Khan       100.00

[642 rows x 2 columns]

In [4]:
run_sql_file(r"C:\Users\ctabd\OneDrive\Desktop\3rd Sem ojt\project_3.1\sql\practice\09_analysis_clean.sql")

ran C:\Users\ctabd\OneDrive\Desktop\3rd Sem ojt\project_3.1\sql\practice\09_analysis_clean.sql

In [5]:
q(""" select * from v_match_totals;""")

,match_id,venue_clean,city_clean,season_year,result,match_winner,player_of_match,toss_winner,toss_decision,first_innings_runs,bat_first_team,chase_won
0,335982,M Chinnaswamy Stadium,Bangalore,2008,win,Kolkata Knight Riders,BB McCullum,Royal Challengers Bangalore,field,222,Kolkata Knight Riders,0
1,1082591,Rajiv Gandhi International Stadium,Hyderabad,2017,win,Sunrisers Hyderabad,Yuvraj Singh,Royal Challengers Bangalore,field,207,Sunrisers Hyderabad,0
2,1082592,Maharashtra Cricket Association Stadium,Pune,2017,win,Rising Pune Supergiant,SPD Smith,Rising Pune Supergiant,field,184,Mumbai Indians,1
3,1082593,Saurashtra Cricket Association Stadium,Rajkot,2017,win,Kolkata Knight Riders,CA Lynn,Kolkata Knight Riders,field,183,Gujarat Lions,1
4,1082594,Holkar Cricket Stadium,Indore,2017,win,Punjab Kings,GJ Maxwell,Punjab Kings,field,163,Rising Pune Supergiant,1
...,...,...,...,...,...,...,...,...,...,...,...,...
1182,1529282,Arun Jaitley Stadium,Delhi,2026,win,Royal Challengers Bangalore,JR Hazlewood,Royal Challengers Bangalore,field,75,Delhi Capitals,1
1183,1529283,Maharaja Yadavindra Singh International Cricke...,New Chandigarh,2026,win,Rajasthan Royals,D Ferreira,Rajasthan Royals,field,222,Punjab Kings,1
1184,1529284,Wankhede Stadium,Mumbai,2026,win,Sunrisers Hyderabad,H Klaasen,Mumbai Indians,bat,243,Mumbai Indians,1
1185,1529285,Narendra Modi Stadium,Ahmedabad,2026,win,Gujarat Titans,JO Holder,Gujarat Titans,field,155,Royal Challengers Bangalore,1
1186,1529286,Sawai Mansingh Stadium,Jaipur,2026,win,Delhi Capitals,KL Rahul,Rajasthan Royals,bat,225,Rajasthan Royals,1

In [6]:
q("""select count(*)from v_match_totals;""")

   count(*)
0      1187

In [7]:
q("""select count(*) from v_innings ;""")

   count(*)
0      2418

In [8]:
q("""select phase, count(*) from v_ball ;""")

       phase  count(*)
0  Powerplay    288051

In [9]:
q("""

--give the list of highest runs scored in ipl history
--top 5
select batter as player,
sum(batter_runs) as total_runs
from v_ball
group by batter
order by total_runs desc
limit 5;""")

      player  total_runs
0    V Kohli        9040
1  RG Sharma        7183
2   S Dhawan        6769
3  DA Warner        6565
4   KL Rahul        5655

In [10]:
q("""

--give the list of players with highest sixes scored in ipl history
--top 10



select batter as player,
sum(case when batter_runs = 6 then 1 else 0 end) as total_sixes
from v_ball
group by batter
order by total_sixes desc
limit 10;""")

           player  total_sixes
0        CH Gayle          357
1       RG Sharma          311
2         V Kohli          307
3        MS Dhoni          264
4  AB de Villiers          251
5       DA Warner          236
6       SV Samson          234
7        KL Rahul          232
8      AD Russell          223
9      KA Pollard          223

In [11]:
q("""
--highest ball faced by a player,total,runs,strike rate

select batter,
            sum(is_legal) as balls,
            sum(batter_runs) as runs,
            round(100.0 * sum(batter_runs) / sum(is_legal), 2) as strike_rate

    from v_ball
    group by batter
    order by balls desc
    limit 10;





""")

       batter  balls  runs  strike_rate
0     V Kohli   6730  9040       134.32
1   RG Sharma   5396  7183       133.12
2    S Dhawan   5302  6769       127.67
3   DA Warner   4675  6565       140.43
4   AM Rahane   4141  5194       125.43
5    KL Rahul   4059  5655       139.32
6    SK Raina   4022  5528       137.44
7    MS Dhoni   3935  5439       138.22
8  RV Uthappa   3782  4952       130.94
9  KD Karthik   3567  4842       135.74

In [12]:
q(""" 
--batter who scored the highest share of runs in boundary

select batter,
            sum(batter_runs)as runs,
            round(100.0*(case when batter_runs in (4,6)
            then batter_runs
            else 0
            end),2)as boundary_perc

from v_ball
group by batter
order by boundary_perc desc
limit 10;""")

                    batter  runs  boundary_perc
0              A Choudhary    25          600.0
1  JPR Scantlebury-Searles     8          600.0
2                KK Cooper   116          600.0
3             M Theekshana    17          600.0
4                RJ Quiney   103          600.0
5                  RR Pant  3742          600.0
6                   SD Lad    15          600.0
7             Sameer Rizvi   381          600.0
8            V Suryavanshi   656          600.0
9            A Raghuvanshi   672          400.0

In [13]:
q("""select * from v_ball""")

,season_id,match_id,batter,bowler,non_striker,over_number,ball_number,batter_runs,extras,total_runs,...,is_super_over,innings,batting_team_id,bowling_team_id,batting_team,bowling_team,phase,is_legal,bowler_runs,bowler_wicket
0,2008,335982,SC Ganguly,P Kumar,BB McCullum,0,0,0,1,1,...,0,1,6,1,Kolkata Knight Riders,Royal Challengers Bangalore,Powerplay,1,0,0
1,2008,335982,BB McCullum,P Kumar,SC Ganguly,0,1,0,0,0,...,0,1,6,1,Kolkata Knight Riders,Royal Challengers Bangalore,Powerplay,1,0,0
2,2008,335982,BB McCullum,P Kumar,SC Ganguly,0,2,0,1,1,...,0,1,6,1,Kolkata Knight Riders,Royal Challengers Bangalore,Powerplay,0,1,0
3,2008,335982,BB McCullum,P Kumar,SC Ganguly,0,3,0,0,0,...,0,1,6,1,Kolkata Knight Riders,Royal Challengers Bangalore,Powerplay,1,0,0
4,2008,335982,BB McCullum,P Kumar,SC Ganguly,0,4,0,0,0,...,0,1,6,1,Kolkata Knight Riders,Royal Challengers Bangalore,Powerplay,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
288046,2026,1529286,T Stubbs,JC Archer,Ashutosh Sharma,18,3,1,0,1,...,0,2,252,134,Delhi Capitals,Rajasthan Royals,Death,1,1,0
288047,2026,1529286,Ashutosh Sharma,JC Archer,T Stubbs,18,4,1,0,1,...,0,2,252,134,Delhi Capitals,Rajasthan Royals,Death,1,1,0
288048,2026,1529286,T Stubbs,JC Archer,Ashutosh Sharma,18,5,4,0,4,...,0,2,252,134,Delhi Capitals,Rajasthan Royals,Death,1,4,0
288049,2026,1529286,Ashutosh Sharma,Brijesh Sharma,T Stubbs,19,0,4,0,4,...,0,2,252,134,Delhi Capitals,Rajasthan Royals,Death,1,4,0
288050,2026,1529286,Ashutosh Sharma,Brijesh Sharma,T Stubbs,19,1,0,1,1,...,0,2,252,134,Delhi Capitals,Rajasthan Royals,Death,0,1,0

In [14]:
q("""SELECT batter,SUM(is_legal) AS balls,SUM(batter_runs) AS runs,
ROUND(100.0* SUM(batter_runs)/SUM(is_legal),2) AS run_rate

FROM v_ball
WHERE phase ='Middle'
GROUP BY batter
HAVING balls> 500
ORDER BY run_rate desc
LIMIT 20;
""")

             batter  balls  runs  run_rate
0          V Sehwag    611  1062    173.81
1        RM Patidar    566   970    171.38
2          N Pooran    848  1351    159.32
3         H Klaasen    697  1099    157.68
4          CH Gayle   1285  2011    156.50
5        AD Russell    767  1182    154.11
6         SR Watson   1302  2006    154.07
7        GJ Maxwell   1163  1780    153.05
8          SE Marsh    971  1448    149.12
9          DR Smith    675  1004    148.74
10  B Sai Sudharsan    694  1031    148.56
11       JC Buttler   1303  1890    145.05
12         SA Yadav   1845  2664    144.39
13     Shubman Gill   1300  1864    143.38
14       RD Gaikwad    780  1093    140.13
15       MA Agarwal    781  1094    140.08
16          VR Iyer    524   731    139.50
17      YBK Jaiswal    582   811    139.35
18     Ishan Kishan   1091  1518    139.14
19         KL Rahul   1740  2412    138.62

In [15]:
q("""SELECT batter,SUM(is_legal) AS balls,SUM(batter_runs) AS runs,
ROUND(100.0* SUM(batter_runs)/SUM(is_legal),2) AS strike_rate

FROM v_ball
WHERE phase ='Death'
GROUP BY batter
HAVING balls> 500
ORDER BY strike_rate desc
LIMIT 20;
""")

            batter  balls  runs  strike_rate
0   AB de Villiers    829  1868       225.33
1          RR Pant    513  1035       201.75
2       AD Russell    724  1432       197.79
3          V Kohli    807  1525       188.97
4       MP Stoinis    521   962       184.64
5        RG Sharma    837  1527       182.44
6         KL Rahul    502   907       180.68
7         MS Dhoni   1965  3468       176.49
8         DJ Bravo    516   909       176.16
9       KD Karthik   1091  1904       174.52
10       DA Miller    835  1454       174.13
11      SO Hetmyer    553   956       172.88
12        SK Raina    521   899       172.55
13       HH Pandya    870  1499       172.30
14      KA Pollard   1180  2032       172.20
15       JP Duminy    516   882       170.93
16       AT Rayudu    692  1179       170.38
17       YK Pathan    696  1126       161.78
18        AR Patel    629   971       154.37
19       RA Jadeja   1240  1882       151.77

In [16]:
q("""SELECT batter,SUM(is_legal) AS balls,SUM(batter_runs) AS runs,
ROUND(100.0* SUM(batter_runs)/SUM(is_legal),2) AS strike_rate

FROM v_ball
WHERE phase ='Powerplay'
GROUP BY batter
HAVING balls> 500
ORDER BY strike_rate desc
LIMIT 20;
""")

             batter  balls  runs  strike_rate
0   Abhishek Sharma    744  1287       172.98
1         SP Narine    688  1174       170.64
2       YBK Jaiswal    984  1579       160.47
3    P Simran Singh    687  1070       155.75
4       JM Bairstow    623   944       151.52
5           PP Shaw    917  1347       146.89
6          V Sehwag   1096  1593       145.35
7           CA Lynn    537   779       145.07
8        JC Buttler   1257  1789       142.32
9       RA Tripathi    721  1013       140.50
10         SA Yadav    704   984       139.77
11        DA Warner   2384  3316       139.09
12  B Sai Sudharsan    609   844       138.59
13     Ishan Kishan   1047  1432       136.77
14     F du Plessis   1670  2281       136.59
15         CH Gayle   1753  2373       135.37
16     AC Gilchrist   1026  1385       134.99
17     Shubman Gill   1420  1912       134.65
18         SK Raina   1162  1552       133.56
19          WP Saha   1045  1389       132.92

In [17]:
q("""
SELECT 
    batter,
    SUM(batter_runs) AS runs,
    SUM(CASE WHEN is_legal = 1 THEN 1 ELSE 0 END) AS balls,
    ROUND(
        100.0 * SUM(batter_runs) /
        SUM(CASE WHEN is_legal = 1 THEN 1 ELSE 0 END),
        2
    ) AS strike_rate
FROM v_ball
WHERE innings=2
GROUP BY batter
HAVING balls>500
ORDER BY strike_rate DESC
LIMIT 10;
""")

            batter  runs  balls  strike_rate
0        SP Narine   869    507       171.40
1       AD Russell  1130    660       171.21
2  Abhishek Sharma  1108    648       170.99
3         N Pooran  1218    729       167.08
4         V Sehwag  1427    869       164.21
5       GJ Maxwell  1164    734       158.58
6   P Simran Singh   832    527       157.87
7       JC Buttler  2289   1461       156.67
8      YBK Jaiswal  1351    875       154.40
9         SA Yadav  2131   1382       154.20

In [18]:
q("""SELECT batter,
        SUM(is_legal) AS balls,
        SUM(CASE WHEN 
            batter_runs=0 AND is_legal=1
            THEN 1 ELSE 0
            END) AS dot_balls,
        ROUND(100.0*SUM(CASE WHEN 
            batter_runs=0 AND is_legal=1
            THEN 1 ELSE 0
            END)/SUM(is_legal),2) AS
            dot_pct

FROM v_ball
WHERE phase='Death'
GROUP BY batter
HAVING balls >=500
ORDER BY dot_pct ASC
LIMIT 5;
""")

           batter  balls  dot_balls  dot_pct
0       JP Duminy    516        104    20.16
1  AB de Villiers    829        175    21.11
2        SK Raina    521        111    21.31
3        KL Rahul    502        110    21.91
4         V Kohli    807        185    22.92

In [19]:
q("""
--how do runs and wickets differ across the three phases of an innings?

select phase,sum(is_legal)as balls,sum(total_runs),
round(6.0*sum(total_runs)/sum(is_legal),2)as runs_per_over,
round(100.0*sum(is_wicket)/sum(is_legal),2)as wicket_perc

from v_ball
group by phase;

""")

       phase   balls  sum(total_runs)  runs_per_over  wicket_perc
0      Death   62205           104056          10.04         8.46
1     Middle  128191           169160           7.92         4.34
2  Powerplay   86921           116397           8.03         4.01

In [20]:
q(""" 
 SELECT over_number+1 AS overs,
 ROUND(6.0*SUM(total_runs)/SUM(is_legal),2) AS runs_per_over
 FROM  v_ball
 GROUP BY over_number
 order BY runs_per_over DESC;

""")

    overs  runs_per_over
0      20          11.39
1      19          10.53
2      18          10.12
3      17           9.46
4      16           9.05
5      15           8.74
6       6           8.68
7       5           8.65
8       4           8.63
9      14           8.43
10      3           8.37
11     13           8.17
12     12           8.13
13     11           7.96
14      9           7.77
15     10           7.66
16      2           7.60
17      8           7.47
18      7           6.98
19      1           6.28

In [21]:
q("""
SELECT
    over_number + 1 AS over,
    SUM(is_wicket) AS wickets
FROM v_ball
GROUP BY over_number
ORDER BY over_number DESC;
""")

    over  wickets
0     20     1433
1     19     1089
2     18     1055
3     17      863
4     16      824
5     15      764
6     14      703
7     13      661
8     12      621
9     11      635
10    10      554
11     9      593
12     8      534
13     7      497
14     6      585
15     5      640
16     4      597
17     3      606
18     2      567
19     1      488

In [22]:
q("""
SELECT bowler,SUM(bowler_wicket) AS wicket 
FROM v_ball
GROUP BY bowler
ORDER BY wicket DESC;
""")

               bowler  wicket
0           YS Chahal     228
1             B Kumar     215
2           SP Narine     199
3           PP Chawla     192
4            R Ashwin     187
..                ...     ...
563       Tilak Varma       0
564       VS Yeligati       0
565    Vivrant Sharma       0
566  Y Gnaneswara Rao       0
567       YBK Jaiswal       0

[568 rows x 2 columns]

In [23]:
q("""
-- Find the most economical bowler

SELECT
    bowler,
    SUM(bowler_runs) AS runs_conceded,
    SUM(is_legal) AS legal_balls,
    ROUND(
        6.0 * SUM(bowler_runs) / SUM(is_legal),
        2
    ) AS economy_rate
FROM v_ball
GROUP BY bowler
HAVING legal_balls > 500
ORDER BY economy_rate ASC
LIMIT 10;
""")

            bowler  runs_conceded  legal_balls  economy_rate
0         A Kumble           1058          965          6.58
1   M Muralitharan           1696         1524          6.68
2       DL Vettori            879          777          6.79
3        SP Narine           5102         4507          6.79
4         DW Steyn           2508         2176          6.92
5          J Botha            800          694          6.92
6         R Sharma           1086          928          7.02
7  Harbhajan Singh           4030         3416          7.08
8       SL Malinga           3366         2827          7.14
9      Rashid Khan           4040         3387          7.16

In [24]:
q(""" 
  --which bowler takes a wicket most oftrn - best strike rate in balls per wicket
  --bowler,total ball,total wicket,ball per wicket

SELECT
    bowler,
    SUM(is_legal) AS total_balls,
    SUM(bowler_wicket) AS total_wickets,
    ROUND(
        1.0 * SUM(is_legal) / SUM(bowler_wicket),
        2
    ) AS balls_per_wicket
FROM v_ball
GROUP BY bowler
HAVING total_wickets > 50
ORDER BY balls_per_wicket ASC
LIMIT 10;
""")

         bowler  total_balls  total_wickets  balls_per_wicket
0    AD Russell         1806            123             14.68
1  JR Hazlewood         1008             65             15.51
2      K Rabada         2112            133             15.88
3      MA Starc         1083             68             15.93
4   Imran Tahir         1316             82             16.05
5      HV Patel         2470            151             16.36
6    SL Malinga         2827            170             16.63
7      DJ Bravo         3120            183             17.05
8     YS Chahal         3941            228             17.29
9    Noor Ahmad          966             55             17.56

In [25]:
q("""
-- Which bowler gives away the fewest boundaries?
SELECT
    bowler,
    SUM(is_legal) AS balls,
    SUM(CASE WHEN total_runs IN (4, 6) THEN 1 ELSE 0 END) AS four_and_six,
    ROUND(
        100.0 * SUM(CASE WHEN total_runs IN (4, 6) THEN 1 ELSE 0 END)
        / SUM(is_legal),
        2
    ) AS boundary_perc
FROM v_ball
GROUP BY bowler
HAVING SUM(is_legal) > 1000
ORDER BY boundary_perc ASC
LIMIT 10;
""")

            bowler  balls  four_and_six  boundary_perc
0   M Muralitharan   1524           173          11.35
1         R Bhatia   1636           190          11.61
2        SP Narine   4507           533          11.83
3         R Ashwin   4710           558          11.85
4         M Kartik   1149           140          12.18
5         SK Warne   1194           148          12.40
6         A Mishra   3371           423          12.55
7         S Nadeem   1415           185          13.07
8      Rashid Khan   3387           443          13.08
9  Harbhajan Singh   3416           447          13.09

In [26]:
q("""
-- Which bowler bowls the most dot balls?
-- bowler, balls, dot_ball, dot_perc

SELECT
    bowler,
    SUM(is_legal) AS balls,
    SUM(CASE WHEN batter_runs = 0 THEN 1 ELSE 0 END) AS dot_ball,
    ROUND(
        100.0 * SUM(CASE WHEN batter_runs = 0 THEN 1 ELSE 0 END)
        / SUM(is_legal),
        2
    ) AS dot_perc
FROM v_ball
WHERE is_legal = 1
GROUP BY bowler
HAVING balls > 1000
ORDER BY dot_ball DESC
LIMIT 10;
""")

            bowler  balls  dot_ball  dot_perc
0          B Kumar   4432      1935     43.66
1        SP Narine   4507      1788     39.67
2         R Ashwin   4710      1663     35.31
3        JJ Bumrah   3517      1485     42.22
4        RA Jadeja   4188      1379     32.93
5        PP Chawla   3850      1358     35.27
6        YS Chahal   3941      1353     34.33
7  Harbhajan Singh   3416      1312     38.41
8      Rashid Khan   3387      1270     37.50
9         UT Yadav   3050      1260     41.31

In [27]:
q("""

SELECT bowler,SUM(is_legal) AS balls,SUM(CASE WHEN total_runs=0 AND is_legal=1
                                THEN 1
                                ELSE 0
                                END) AS dot_balls,
                            ROUND(100.0*SUM(CASE WHEN total_runs=0 AND is_legal=1
                            THEN 1
                            ELSE 0
                            END)/SUM(is_legal),2) AS dot_perc 
                            
FROM v_ball
GROUP BY bowler
HAVING balls >=1000
ORDER BY dot_perc DESC
LIMIT 10;
""")

         bowler  balls  dot_balls  dot_perc
0      DW Steyn   2176       1019     46.83
1     JC Archer   1440        627     43.54
2      MM Patel   1355        590     43.54
3      M Morkel   1629        708     43.46
4    MG Johnson   1232        533     43.26
5  JR Hazlewood   1008        434     43.06
6       P Kumar   2524       1075     42.59
7     DL Chahar   1954        827     42.32
8      RP Singh   1775        744     41.92
9       A Nehra   1908        798     41.82

In [28]:
q("""
SELECT
    CASE
        WHEN bowler_type LIKE 'Left%'
        THEN 'Left arm'
        ELSE 'Right arm'
    END AS arm,

    batsman_type,

    ROUND(
        6.0 * SUM(bowler_runs) / SUM(is_legal),
        2
    ) AS economy,

    ROUND(
        100.0 * SUM(bowler_wicket) / SUM(is_legal),
        2
    ) AS wicket_pct

FROM v_ball

WHERE TRIM(COALESCE(bowler_type, '')) <> ''
  AND batsman_type IS NOT NULL

GROUP BY arm, batsman_type;
""")

         arm    batsman_type  economy  wicket_pct
0   Left arm   Left hand Bat     8.81        5.13
1   Left arm  Right hand Bat     8.49        4.97
2  Right arm   Left hand Bat     8.33        4.46
3  Right arm  Right hand Bat     8.16        4.78

In [29]:
q("""
SELECT
    bowler,
    SUM(bowler_wicket) AS wicket,
    ROUND(
        100.0 * SUM(bowler_wicket) / SUM(is_legal),
        2
    ) AS wicket_perc
FROM v_ball
WHERE bowler_type LIKE '%Legbreak%'
   OR bowler_type LIKE '%Offbreak%'
   OR bowler_type LIKE '%Orthodox%'
   OR bowler_type LIKE '%Wrist spin%'
   OR bowler_type LIKE '%Googly%'
GROUP BY bowler
HAVING SUM(is_legal) >= 1000
ORDER BY wicket DESC
LIMIT 10;
""")

            bowler  wicket  wicket_perc
0        YS Chahal     228         5.79
1        SP Narine     199         4.42
2        PP Chawla     192         4.99
3         R Ashwin     187         3.97
4        RA Jadeja     177         4.23
5         A Mishra     174         5.16
6      Rashid Khan     168         4.96
7  Harbhajan Singh     150         4.39
8         AR Patel     136         3.90
9    Kuldeep Yadav     109         4.90

In [30]:
q("""
-- We need a death-overs bowler who is cheapest in overs 16 to 20

SELECT
    bowler,
    SUM(is_legal) AS balls,
    SUM(bowler_runs) AS bowler_runs,
    ROUND(
        6.0 * SUM(bowler_runs) / SUM(is_legal),
        2
    ) AS economy
FROM v_ball
WHERE over_number BETWEEN 16 AND 20
  AND is_legal = 1
GROUP BY bowler
HAVING balls > 300
ORDER BY economy ASC
LIMIT 10;
""")

        bowler  balls  bowler_runs  economy
0   SL Malinga    917         1132     7.41
1    SP Narine    763          989     7.78
2    JJ Bumrah   1237         1652     8.01
3  M Pathirana    314          427     8.16
4    CH Morris    586          806     8.25
5  Rashid Khan    360          500     8.33
6     DW Steyn    532          744     8.39
7      A Nehra    419          593     8.49
8       Z Khan    535          769     8.62
9     R Ashwin    337          486     8.65

In [31]:
q("""
-- We need a powerplay strike bowler
-- Who takes most wickets in overs 1 to 6

SELECT
    bowler,
    SUM(is_legal) AS balls,
    SUM(bowler_wicket) AS wicket,
    ROUND(
        100.0 * SUM(bowler_wicket) / SUM(is_legal),
        2
    ) AS wicket_perc
FROM v_ball
WHERE over_number BETWEEN 0 AND 5
  AND is_legal = 1
GROUP BY bowler
HAVING balls > 300
ORDER BY wicket DESC
LIMIT 10;
""")

           bowler  balls  wicket  wicket_perc
0         B Kumar   2453      89         3.63
1        TA Boult   1644      72         4.38
2       DL Chahar   1527      67         4.39
3  Sandeep Sharma   1728      64         3.70
4        UT Yadav   1446      58         4.01
5        I Sharma   1521      57         3.75
6  Mohammed Shami   1584      57         3.60
7          Z Khan   1292      52         4.02
8  Mohammed Siraj   1326      50         3.77
9        R Ashwin   1252      48         3.83

In [32]:
q("""
SELECT
    bowler,
    SUM(is_legal) AS balls,
    SUM(is_legal AND total_runs = 0) AS dot_balls,
    ROUND(100.0 * SUM(is_legal AND total_runs = 0) / SUM(is_legal), 2) AS dot_perc
FROM v_ball
WHERE phase = 'Death'
GROUP BY bowler
HAVING balls >= 300
ORDER BY dot_perc DESC
LIMIT 10;
""")

              bowler  balls  dot_balls  dot_perc
0          SP Narine   1075        397     36.93
1           CV Varun    310        112     36.13
2         MG Johnson    302        108     35.76
3        Rashid Khan    594        208     35.02
4           DW Steyn    634        218     34.38
5          PP Chawla    444        150     33.78
6           K Rabada    660        222     33.64
7  M Prasidh Krishna    542        182     33.58
8           A Mishra    521        167     32.05
9           MA Starc    333        106     31.83

In [33]:
run_sql_file(r"C:\Users\ctabd\OneDrive\Desktop\3rd Sem ojt\project_3.1\sql\practice\08_matches_clean.sql")

ran C:\Users\ctabd\OneDrive\Desktop\3rd Sem ojt\project_3.1\sql\practice\08_matches_clean.sql

In [34]:
q("""
-- What do captains actually choose when they win the toss?
-- toss_decision, total_count, perc

SELECT
    toss_decision,
    COUNT(*) AS total_count,
    ROUND(
        100.0 * COUNT(*) / (SELECT COUNT(*) FROM matches_clean),
        2
    ) AS perc
FROM  matches_clean
GROUP BY toss_decision;
""")

  toss_decision  total_count   perc
0           bat          412  33.99
1         field          800  66.01

In [35]:
q("""select count(*) from matches_clean;""")

   count(*)
0      1212

In [36]:
q("""
SELECT
    toss_winner,
    COUNT(*) AS toss_won
FROM matches_clean
GROUP BY toss_winner
ORDER BY toss_won DESC;
""")

                    toss_winner  toss_won
0                Mumbai Indians       156
1                Delhi Capitals       145
2           Sunrisers Hyderabad       139
3              Rajasthan Royals       134
4   Royal Challengers Bangalore       132
5         Kolkata Knight Riders       132
6           Chennai Super Kings       130
7                  Punjab Kings       126
8                Gujarat Titans        33
9          Lucknow Super Giants        29
10                Pune Warriors        20
11                Gujarat Lions        15
12       Rising Pune Supergiant        13
13         Kochi Tuskers Kerala         8

In [37]:
q("""
SELECT ROUND(AVG(first_innings_runs), 2) AS average_first_innings_score
FROM v_match_totals;
""")

   average_first_innings_score
0                       168.19

In [38]:
q("""
SELECT
    innings,
    ROUND(6.0 * SUM(total_runs) / SUM(is_legal), 2) AS run_rate
FROM v_ball
WHERE innings IN (1, 2)
GROUP BY innings
ORDER BY innings;
""")

   innings  run_rate
0        1      8.49
1        2      8.37

In [39]:
q("""
SELECT
    CASE innings
        WHEN 1 THEN 'Batting first'
        WHEN 2 THEN 'Batting second'
    END AS batting_order,
    ROUND(AVG(wickets), 2) AS average_wickets_lost
FROM v_innings
GROUP BY innings
ORDER BY average_wickets_lost DESC;
""")

    batting_order  average_wickets_lost
0   Batting first                  6.13
1  Batting second                  5.70

In [40]:
q("""
SELECT
    COUNT(*) AS match_with_200plus,
    SUM(chase_won) AS successfully_chased 

    FROM v_match_totals
    WHERE first_innings_runs >=200;
    
""")

   match_with_200plus  successfully_chased
0                 198                   46

In [41]:
q("""
SELECT
    MAX(CASE WHEN chase_won = 0 THEN first_innings_runs END) AS biggest_defend,
    MAX(CASE WHEN chase_won = 1 THEN first_innings_runs END) AS biggest_chased
FROM v_match_totals;
""")

   biggest_defend  biggest_chased
0             287             264

In [42]:
q("""
SELECT
    venue_clean,COUNT(*) AS match_count
FROM matches_clean
GROUP BY venue_clean
order by match_count desc ;
""")

                                          venue_clean  match_count
0                                    Wankhede Stadium          130
1                               M Chinnaswamy Stadium          104
2                                        Eden Gardens          104
3                              MA Chidambaram Stadium           95
4                  Rajiv Gandhi International Stadium           87
5                              Sawai Mansingh Stadium           66
6                                    Feroz Shah Kotla           60
7                 Dubai International Cricket Stadium           46
8                                Arun Jaitley Stadium           41
9                               Narendra Modi Stadium           37
10                         Dr DY Patil Sports Academy           37
11                 Punjab Cricket Association Stadium           35
12            Maharashtra Cricket Association Stadium           35
13                               Sheikh Zayed Stadium           29
14                            Sharjah Cricket Stadium           28
15                                  Brabourne Stadium           27
16       Punjab Cricket Association IS Bindra Stadium           26
17  Bharat Ratna Shri Atal Bihari Vajpayee Ekana C...           26
18  Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket St...           17
19                         Subrata Roy Sahara Stadium           16
20  Maharaja Yadavindra Singh International Cricke...           15
21                                          Kingsmead           15
22       Himachal Pradesh Cricket Association Stadium           15
23                                    SuperSport Park           12
24                               Sardar Patel Stadium           12
25             Saurashtra Cricket Association Stadium           10
26                             Holkar Cricket Stadium            9
27                              Zayed Cricket Stadium            8
28                              New Wanderers Stadium            8
29                          Barsapara Cricket Stadium            8
30                                   St George's Park            7
31                                           Newlands            7
32                 JSCA International Stadium Complex            7
33                                   Barabati Stadium            7
34   Shaheed Veer Narayan Singh International Stadium            6
35                                      Nehru Stadium            5
36                                         Green Park            4
37               Vidarbha Cricket Association Stadium            3
38                              De Beers Diamond Oval            3
39                                       Buffalo Park            3
40                                    OUTsurance Oval            2

In [43]:
q("""SELECT m.venue_clean,
       COUNT(DISTINCT m.match_id) AS matches,
       ROUND(AVG(i.runs), 2) AS avg_score
FROM matches_clean m
JOIN v_innings i ON i.match_id = m.match_id
GROUP BY m.venue_clean
HAVING matches >= 25
ORDER BY avg_score DESC
LIMIT 10;""")

                                         venue_clean  matches  avg_score
0                               Arun Jaitley Stadium       41     180.04
1                              Narendra Modi Stadium       37     177.82
2                                  Brabourne Stadium       27     172.31
3       Punjab Cricket Association IS Bindra Stadium       26     170.71
4  Bharat Ratna Shri Atal Bihari Vajpayee Ekana C...       26     167.59
5                                   Wankhede Stadium      130     166.95
6                              M Chinnaswamy Stadium      104     165.67
7                             Sawai Mansingh Stadium       66     161.11
8                 Rajiv Gandhi International Stadium       87     161.06
9                                       Eden Gardens      104     160.94

In [44]:
q("""
SELECT
    match_winner AS team,
    COUNT(*) AS wins
FROM matches_clean
WHERE RESULT='win'
GROUP BY match_winner
ORDER BY wins DESC
LIMIT 10;
""")

                          team  wins
0               Mumbai Indians   153
1          Chennai Super Kings   145
2  Royal Challengers Bangalore   138
3        Kolkata Knight Riders   136
4          Sunrisers Hyderabad   128
5                 Punjab Kings   125
6               Delhi Capitals   122
7             Rajasthan Royals   120
8               Gujarat Titans    42
9         Lucknow Super Giants    32

In [45]:
q("""
SELECT
    batting_team,
    SUM(is_legal) AS legal_balls,
    SUM(total_runs) AS runs,
    ROUND(6.0 * SUM(total_runs) / SUM(is_legal), 2) AS run_rate
FROM v_ball
WHERE phase = 'Powerplay'
GROUP BY batting_team
HAVING SUM(is_legal) >= 3000
ORDER BY run_rate DESC
LIMIT 10;
""")

                  batting_team  legal_balls   runs  run_rate
0                 Punjab Kings         9755  13344      8.21
1          Sunrisers Hyderabad        10034  13712      8.20
2             Rajasthan Royals         8768  11797      8.07
3               Delhi Capitals         9893  13237      8.03
4        Kolkata Knight Riders         9738  13016      8.02
5               Mumbai Indians        10257  13561      7.93
6  Royal Challengers Bangalore        10008  13196      7.91
7          Chennai Super Kings         9324  12198      7.85

In [46]:
q("""
SELECT
    batting_team AS team,
    SUM(CASE WHEN batter_runs IN (4, 6) THEN batter_runs ELSE 0 END) AS boundary_runs,
    SUM(total_runs) AS total_runs,
    ROUND(
        100.0 * SUM(CASE WHEN batter_runs IN (4, 6) THEN batter_runs ELSE 0 END)
        / SUM(batter_runs), 2
    ) AS boundary_percentage
FROM v_ball
GROUP BY batting_team
HAVING SUM(is_legal) >=10000
ORDER BY boundary_percentage DESC
LIMIT 10;
""")

                          team  boundary_runs  total_runs  boundary_percentage
0               Mumbai Indians          27486       46517                62.30
1        Kolkata Knight Riders          24846       42540                61.84
2                 Punjab Kings          25986       44352                61.67
3  Royal Challengers Bangalore          26220       44890                61.44
4             Rajasthan Royals          22718       39159                60.90
5               Delhi Capitals          24688       43297                59.97
6          Chennai Super Kings          24186       42557                59.80
7          Sunrisers Hyderabad          24982       44948                58.50

In [47]:
q("""select * from matches_clean;""")

,match_id,venue_clean,city_clean,season_year,team1,team2,result,match_winner,player_of_match,toss_winner,toss_decision
0,335982,M Chinnaswamy Stadium,Bangalore,2008,Royal Challengers Bangalore,Kolkata Knight Riders,win,Kolkata Knight Riders,BB McCullum,Royal Challengers Bangalore,field
1,1082591,Rajiv Gandhi International Stadium,Hyderabad,2017,Sunrisers Hyderabad,Royal Challengers Bangalore,win,Sunrisers Hyderabad,Yuvraj Singh,Royal Challengers Bangalore,field
2,1082592,Maharashtra Cricket Association Stadium,Pune,2017,Rising Pune Supergiant,Mumbai Indians,win,Rising Pune Supergiant,SPD Smith,Rising Pune Supergiant,field
3,1082593,Saurashtra Cricket Association Stadium,Rajkot,2017,Gujarat Lions,Kolkata Knight Riders,win,Kolkata Knight Riders,CA Lynn,Kolkata Knight Riders,field
4,1082594,Holkar Cricket Stadium,Indore,2017,Punjab Kings,Rising Pune Supergiant,win,Punjab Kings,GJ Maxwell,Punjab Kings,field
...,...,...,...,...,...,...,...,...,...,...,...
1207,1529282,Arun Jaitley Stadium,Delhi,2026,Delhi Capitals,Royal Challengers Bangalore,win,Royal Challengers Bangalore,JR Hazlewood,Royal Challengers Bangalore,field
1208,1529283,Maharaja Yadavindra Singh International Cricke...,New Chandigarh,2026,Punjab Kings,Rajasthan Royals,win,Rajasthan Royals,D Ferreira,Rajasthan Royals,field
1209,1529284,Wankhede Stadium,Mumbai,2026,Mumbai Indians,Sunrisers Hyderabad,win,Sunrisers Hyderabad,H Klaasen,Mumbai Indians,bat
1210,1529285,Narendra Modi Stadium,Ahmedabad,2026,Royal Challengers Bangalore,Gujarat Titans,win,Gujarat Titans,JO Holder,Gujarat Titans,field
1211,1529286,Sawai Mansingh Stadium,Jaipur,2026,Rajasthan Royals,Delhi Capitals,win,Delhi Capitals,KL Rahul,Rajasthan Royals,bat

In [48]:
q("""select player_of_match as player,
count(*) as awards
from matches_clean 
where player_of_match is not null
group by player_of_match
order by awards desc
limit 10;""")

           player  awards
0  AB de Villiers      25
1        CH Gayle      22
2       RG Sharma      21
3         V Kohli      20
4        MS Dhoni      18
5       DA Warner      18
6       SP Narine      17
7       RA Jadeja      17
8        KL Rahul      17
9       YK Pathan      16

In [49]:
q("""
SELECT
    phase,
    wicket_kind,
    COUNT(*) AS wickets
FROM v_ball
WHERE is_wicket = 1
  AND wicket_kind IN ('caught', 'bowled', 'run out')
GROUP BY phase, wicket_kind
ORDER BY phase,wickets DESC;
""")

       phase wicket_kind  wickets
0      Death      caught     3289
1      Death      bowled      877
2      Death     run out      634
3     Middle      caught     3484
4     Middle      bowled      909
5     Middle     run out      344
6  Powerplay      caught     2272
7  Powerplay      bowled      612
8  Powerplay     run out      189

In [50]:
q("""
-- Which batter is most often run out?
-- player_name, run_out_count

SELECT
    player_out AS player_name,
    COUNT(*) AS run_out_count
FROM v_ball
WHERE wicket_kind = 'run out'
GROUP BY player_out
ORDER BY run_out_count DESC
LIMIT 10;
""")

       player_name  run_out_count
0         S Dhawan             16
1        G Gambhir             16
2         SK Raina             15
3       KD Karthik             15
4        AT Rayudu             15
5   AB de Villiers             14
6          M Vijay             12
7     F du Plessis             12
8        YK Pathan             11
9  Y Venugopal Rao             11

In [51]:
q("""
-- How many matches were played each season?

SELECT
    season_year,
    COUNT(DISTINCT match_id) AS matches
FROM matches_clean
GROUP BY season_year
ORDER BY season_year;
""")

    season_year  matches
0          2008       58
1          2009       57
2          2010       60
3          2011       73
4          2012       74
5          2013       76
6          2014       60
7          2015       59
8          2016       60
9          2017       59
10         2018       60
11         2019       60
12         2020       60
13         2021       60
14         2022       74
15         2023       74
16         2024       71
17         2025       74
18         2026       43

In [52]:
q("""
SELECT
    bowler,batter,
    COUNT(*) AS dismissals
FROM v_ball
WHERE bowler_wicket = 1
GROUP BY bowler,batter
ORDER BY dismissals DESC
""")

               bowler           batter  dismissals
0           SP Narine        RG Sharma           8
1            A Mishra        RG Sharma           7
2             B Kumar        AM Rahane           7
3           JJ Bumrah          RR Pant           7
4           MM Sharma        AT Rayudu           7
...               ...              ...         ...
10305  Zeeshan Ansari  B Sai Sudharsan           1
10306  Zeeshan Ansari     F du Plessis           1
10307  Zeeshan Ansari  J Fraser-McGurk           1
10308  Zeeshan Ansari         KL Rahul           1
10309  Zeeshan Ansari         WG Jacks           1

[10310 rows x 3 columns]

In [53]:
q("""
-- Find an opener who scores fast and survives the powerplay

SELECT
    batter,
    SUM(is_legal) AS balls,
    SUM(batter_runs) AS runs,
    ROUND(100.0 * SUM(batter_runs) / SUM(is_legal), 2) AS sr
FROM v_ball
WHERE phase = 'Powerplay'
  AND is_wicket = 0
GROUP BY batter
HAVING balls >= 500
ORDER BY sr DESC
LIMIT 10;
""")

            batter  balls  runs      sr
0        SP Narine    640  1174  183.44
1  Abhishek Sharma    712  1287  180.76
2      YBK Jaiswal    948  1579  166.56
3   P Simran Singh    658  1070  162.61
4      JM Bairstow    601   944  157.07
5          PP Shaw    866  1347  155.54
6         V Sehwag   1036  1593  153.76
7          CA Lynn    520   779  149.81
8      RA Tripathi    685  1013  147.88
9       JC Buttler   1216  1788  147.04

In [54]:
q("""
select distinct * from v_ball;



""")

,season_id,match_id,batter,bowler,non_striker,over_number,ball_number,batter_runs,extras,total_runs,...,is_super_over,innings,batting_team_id,bowling_team_id,batting_team,bowling_team,phase,is_legal,bowler_runs,bowler_wicket
0,2008,335982,SC Ganguly,P Kumar,BB McCullum,0,0,0,1,1,...,0,1,6,1,Kolkata Knight Riders,Royal Challengers Bangalore,Powerplay,1,0,0
1,2008,335982,BB McCullum,P Kumar,SC Ganguly,0,1,0,0,0,...,0,1,6,1,Kolkata Knight Riders,Royal Challengers Bangalore,Powerplay,1,0,0
2,2008,335982,BB McCullum,P Kumar,SC Ganguly,0,2,0,1,1,...,0,1,6,1,Kolkata Knight Riders,Royal Challengers Bangalore,Powerplay,0,1,0
3,2008,335982,BB McCullum,P Kumar,SC Ganguly,0,3,0,0,0,...,0,1,6,1,Kolkata Knight Riders,Royal Challengers Bangalore,Powerplay,1,0,0
4,2008,335982,BB McCullum,P Kumar,SC Ganguly,0,4,0,0,0,...,0,1,6,1,Kolkata Knight Riders,Royal Challengers Bangalore,Powerplay,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
288046,2026,1529286,T Stubbs,JC Archer,Ashutosh Sharma,18,3,1,0,1,...,0,2,252,134,Delhi Capitals,Rajasthan Royals,Death,1,1,0
288047,2026,1529286,Ashutosh Sharma,JC Archer,T Stubbs,18,4,1,0,1,...,0,2,252,134,Delhi Capitals,Rajasthan Royals,Death,1,1,0
288048,2026,1529286,T Stubbs,JC Archer,Ashutosh Sharma,18,5,4,0,4,...,0,2,252,134,Delhi Capitals,Rajasthan Royals,Death,1,4,0
288049,2026,1529286,Ashutosh Sharma,Brijesh Sharma,T Stubbs,19,0,4,0,4,...,0,2,252,134,Delhi Capitals,Rajasthan Royals,Death,1,4,0
288050,2026,1529286,Ashutosh Sharma,Brijesh Sharma,T Stubbs,19,1,0,1,1,...,0,2,252,134,Delhi Capitals,Rajasthan Royals,Death,0,1,0

In [55]:
run_sql_file(r"C:\Users\ctabd\OneDrive\Desktop\3rd Sem ojt\project_3.1\sql\practice\08_matches_clean.sql")

ran C:\Users\ctabd\OneDrive\Desktop\3rd Sem ojt\project_3.1\sql\practice\08_matches_clean.sql