In [9]:
import sqlite3
import pandas as pd

con = sqlite3.connect('C:\\Users\\ctabd\\OneDrive\\Desktop\\3rd Sem\\project_3.1\\2_IPL_Cricket\\ipl.db')

def q(sql):
    return pd.read_sql_query(sql, con)

In [10]:
def run_sql_file(path):
    with open(path,'r')as f:
        script=f.read()
    con.executescript(script)
    con.commit()
    print('ran',path)

In [11]:
q("""
-- What is the strike rate of every batter in the death overs

SELECT
    batter,
    ROUND(
        100.0 * SUM(batter_runs) /
        SUM(
            CASE
                WHEN is_wide_ball = 0
                 AND is_no_ball = 0
                THEN 1
                ELSE 0
            END
        ),
        2
    ) AS strike_rate
FROM deliveries
WHERE over_number >= 15
  AND is_super_over = 0
GROUP BY batter;
""")

             batter  strike_rate
0    A Ashish Reddy       146.58
1          A Badoni       165.03
2        A Chandila        57.14
3          A Chopra        50.00
4       A Choudhary       125.00
..              ...          ...
637      Yash Dayal        50.00
638   Yashpal Singh       130.77
639   Yudhvir Singh       166.67
640    Yuvraj Singh       183.40
641          Z Khan       100.00

[642 rows x 2 columns]

In [12]:
run_sql_file(r"C:\Users\ctabd\OneDrive\Desktop\3rd Sem\project_3.1\sql\practice\09_analysis_clean.sql")

ran C:\Users\ctabd\OneDrive\Desktop\3rd Sem\project_3.1\sql\practice\09_analysis_clean.sql

In [13]:
q(""" select * from v_match_totals;""")

,match_id,venue_clean,city_clean,season_year,result,match_winner,player_of_match,toss_decision,first_innings_runs,bat_first_team,chase_won
0,335982,M Chinnaswamy Stadium,Bangalore,2008,win,Kolkata Knight Riders,BB McCullum,field,222,Kolkata Knight Riders,0
1,1082591,Rajiv Gandhi International Stadium,Hyderabad,2017,win,Sunrisers Hyderabad,Yuvraj Singh,field,207,Sunrisers Hyderabad,0
2,1082592,Maharashtra Cricket Association Stadium,Pune,2017,win,Rising Pune Supergiant,SPD Smith,field,184,Mumbai Indians,1
3,1082593,Saurashtra Cricket Association Stadium,Rajkot,2017,win,Kolkata Knight Riders,CA Lynn,field,183,Gujarat Lions,1
4,1082594,Holkar Cricket Stadium,Indore,2017,win,Punjab Kings,GJ Maxwell,field,163,Rising Pune Supergiant,1
...,...,...,...,...,...,...,...,...,...,...,...
1182,1529282,Arun Jaitley Stadium,Delhi,2026,win,Royal Challengers Bangalore,JR Hazlewood,field,75,Delhi Capitals,1
1183,1529283,Maharaja Yadavindra Singh International Cricke...,New Chandigarh,2026,win,Rajasthan Royals,D Ferreira,field,222,Punjab Kings,1
1184,1529284,Wankhede Stadium,Mumbai,2026,win,Sunrisers Hyderabad,H Klaasen,bat,243,Mumbai Indians,1
1185,1529285,Narendra Modi Stadium,Ahmedabad,2026,win,Gujarat Titans,JO Holder,field,155,Royal Challengers Bangalore,1
1186,1529286,Sawai Mansingh Stadium,Jaipur,2026,win,Delhi Capitals,KL Rahul,bat,225,Rajasthan Royals,1

In [14]:
q("""select count(*)from v_match_totals;""")

   count(*)
0      1187

In [15]:
q("""select count(*) from v_innings ;""")

   count(*)
0      2418

In [16]:
q("""select phase, count(*) from v_ball ;""")

       phase  count(*)
0  Powerplay    288051